In [1]:
import numpy as np
import cv2
from skimage import color
import random as rand

## Problem 1

In [2]:
#create salt and pepper image utilizing random function and comparing 
#percent of noise desired with the randomly generated number
image = cv2.imread('5_1.bmp')
image2hsv = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)
x, y, z = image2hsv.shape
perc = 0.15
opp_perc = 1 - perc

for i in range(x):
    for j in range(y):
        pick = rand.random()
        if pick < perc:
            image2hsv[i,j,2] = 0
        elif pick > opp_perc:
            image2hsv[i,j,2] = 255
        else:
            image2hsv[i,j,2] = image2hsv[i,j,2]
    

sp_image = image2hsv
sp_image2 = cv2.cvtColor(sp_image, cv2.COLOR_HSV2BGR)
cv2.imshow('sp_image', sp_image2)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [3]:
#Low Pass Filter
LPF = 1/16 * np.ones([4,4])
reduced_im = cv2.filter2D(image2hsv, -1, LPF)

display_im = cv2.cvtColor(reduced_im, cv2.COLOR_HSV2BGR)
cv2.imshow('Low Pass Filtered Image', display_im)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Comments 
This filter basically blurs the photo based on the size of the filter. The bigger the size using my method, the more blur that occurs

In [5]:
#Median Filter
v_channel = sp_image[:,:,2]

scanImage = cv2.copyMakeBorder(v_channel, 1, 1, 1, 1, cv2.BORDER_REPLICATE)

for i in range(x):                           
    for j in range(y):
        array = scanImage[i:i+3, j:j+3]
        value = np.median(array)
        v_channel[i,j] = value


median_image = np.dstack((sp_image[:,:,0], sp_image[:,:,1], v_channel[:,:]))
med_image = cv2.cvtColor(median_image, cv2.COLOR_HSV2BGR)
cv2.imshow('Median Filtered Image', med_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Comments
This filter actually cleans up the image a good amount. Once again the size of the filter affets to quality of the filtering. The bigger the size of the filter the better the result

## Problem 2

In [113]:
image = cv2.imread('5_2.bmp')
image_gray = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)
image_v = image_gray[:,:,2]

A = 2
boost = np.array([-1, -1, -1, -1, 8 + A, -1, -1, -1, -1])
boost = boost.reshape((3,3))
print(boost)

conv_v = cv2.filter2D(image_v, -1, boost)
new_image = np.dstack((image_gray[:,:,0], image_gray[:,:,1], conv_v[:,:]))
new_color = cv2.cvtColor(new_image, cv2.COLOR_HSV2BGR)
cv2.imshow('Boosted Image', new_color)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[-1 -1 -1]
 [-1 10 -1]
 [-1 -1 -1]]
